{{-- Hand-made dark theme fixes, on top of the rules generated by scripts/dark-theme/generate.py.
     !important so they win over the generated per-page blocks, which load later in the page. --}}
<style id="rk-dark-fixes">
html[data-theme="dark"] { color-scheme: dark; }

/* Soft white glows behind pages: much fainter on a dark background */
html[data-theme="dark"] .bg-blob { opacity: 0.12 !important; }

/* Reminder / history chips get their colours from JavaScript (light pastel background + coloured text).
   In dark mode: tint the chip from its own text colour instead, and lift the text a little. */
html[data-theme="dark"] .reminder-type,
html[data-theme="dark"] .history-type {
  background: color-mix(in srgb, currentColor 18%, transparent) !important;
  filter: brightness(1.35);
}
html[data-theme="dark"] .reminder-dot,
html[data-theme="dark"] .history-icon { background: rgba(148, 163, 184, 0.14) !important; }
html[data-theme="dark"] .reminder-status,
html[data-theme="dark"] .history-status { filter: brightness(1.3); }

/* Reminder cards are peach on mobile in light mode; in dark mode use the normal card surface */
html[data-theme="dark"] .reminder-card:not(.selected) { background: #172233 !important; border-color: #243247 !important; }

html[data-theme="dark"] .timeline-card:has(input[type=checkbox]:checked) { background: #3a1d22 !important; border-color: #7f1d1d !important; }

/* Date & time picker (partials/rk-picker): navy "selected" states become teal so they stand out on a dark sheet */
html[data-theme="dark"] .rkp-d.out, html[data-theme="dark"] .rkp-d.past { color: #475569 !important; }
html[data-theme="dark"] .rkp-d.sel,
html[data-theme="dark"] .rkp-ampm button.on,
html[data-theme="dark"] .rkp-days button.on { background: #2ec4c6 !important; color: #07202a !important; }

/* RakanKampus button (Reminders / Timetable): the navy robot needs a light backing on a dark button */
html[data-theme="dark"] .ai-fab .ai-fab-logo { background: #ffffff; border-radius: 50%; padding: 2px; }

/* Autofilled inputs keep Chrome's light yellow otherwise */
html[data-theme="dark"] input:-webkit-autofill {
  -webkit-text-fill-color: #e2e8f0;
  -webkit-box-shadow: 0 0 0 1000px #172233 inset !important;
}
</style>
