services:
  - type: web
    name: rakankampus
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: singapore
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 80
      - key: APP_NAME
        value: RakanKampus
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: rakankampus-db
          property: connectionString
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: FILESYSTEM_DISK
        value: local
      - key: GROQ_API_KEY
        sync: false
      - key: VAPID_PUBLIC_KEY
        sync: false
      - key: VAPID_PRIVATE_KEY
        sync: false
      - key: VAPID_SUBJECT
        sync: false
      - key: CRON_TOKEN
        generateValue: true

databases:
  - name: rakankampus-db
    plan: free
    region: singapore
    databaseName: rakankampus
    user: rakankampus
