<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @include('partials.pwa-head')
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ __('Appearance') }}</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script>
        tailwind.config = {
            theme: {
                extend: {
                    colors: {
                        indigo: {
                            50: '#e6fbfa',
                            100: '#dbeeee',
                            200: '#b8e6e6',
                            300: '#94a3b8',
                            400: '#64748b',
                            500: '#0d9488',
                            600: '#0d9488',
                            700: '#0f766e',
                            900: '#14213d',
                        },
                    },
                },
            },
        };
    </script>
    <style>
        html, body { overflow-x: hidden; }
        body {
            background: linear-gradient(120deg, #14213d, #1b3a5c, #2ec4c6, #14213d);
    background-size: 300% 300%;
    animation: gradientShift 15s ease infinite;
        }
        .bg-blob {
            position: fixed;
            border-radius: 9999px;
            filter: blur(50px);
            opacity: 0.5;
            z-index: -1;
            pointer-events: none;
            animation: blobFloat 16s ease-in-out infinite;
        }
        .bg-blob.b1 { width: 260px; height: 260px; top: -70px; left: -80px; background: rgba(255,255,255,0.28); animation-duration: 17s; }
        .bg-blob.b2 { width: 220px; height: 220px; top: 35%; right: -90px; background: rgba(255,255,255,0.20); animation-duration: 20s; animation-delay: -4s; }
        .bg-blob.b3 { width: 200px; height: 200px; bottom: -60px; left: 15%; background: rgba(255,255,255,0.24); animation-duration: 15s; animation-delay: -8s; }
        @keyframes blobFloat {
            0%, 100% { transform: translate(0, 0) scale(1); }
            50% { transform: translate(18px, -26px) scale(1.06); }
        }
        @keyframes fadeInUp {
            from { opacity: 0; transform: translateY(14px); }
            to { opacity: 1; transform: translateY(0); }
        }
        body > div:not(.bg-blob) { animation: fadeInUp 0.45s ease both; }

        .page-header {
            display: flex;
            align-items: center;
            gap: 12px;
            padding: 20px 20px 18px;
            position: relative;
            z-index: 1;
        }
        .page-header .back-btn {
            width: 38px; height: 38px; min-width: 38px; border-radius: 50%;
            background: rgba(255,255,255,0.12);
            display: flex; align-items: center; justify-content: center;
            color: #fff; text-decoration: none; transition: background 0.15s ease;
        }
        .page-header .back-btn:hover { background: rgba(255,255,255,0.2); }
        .page-header .back-btn svg { width: 18px; height: 18px; stroke: currentColor; }
        .page-header h1 { font-size: 18px; font-weight: 800; color: #fff; margin: 0; }
        .page-header p { font-size: 12.5px; color: #bfe9ea; margin: 2px 0 0; }

  @keyframes gradientShift {
    0% { background-position: 0% 50%; }
    50% { background-position: 100% 50%; }
    100% { background-position: 0% 50%; }
  }

        .theme-preview { width: 64px; height: 44px; border-radius: 10px; overflow: hidden; display: flex; flex-shrink: 0; border: 1px solid rgba(15,29,46,.12); }
        .theme-preview .side { width: 16px; }
        .theme-preview .main { flex: 1; padding: 6px; display: flex; flex-direction: column; gap: 4px; }
        .theme-preview .bar { height: 5px; border-radius: 3px; }
        .tp-light .side { background: #14213d; } .tp-light .main { background: #f8fafc; } .tp-light .bar { background: #cbd5e1; } .tp-light .bar.acc { background: #2ec4c6; width: 60%; }
        .tp-dark .side { background: #070d16; } .tp-dark .main { background: #111a27; } .tp-dark .bar { background: #334155; } .tp-dark .bar.acc { background: #2ec4c6; width: 60%; }
        .tp-system .main { background: linear-gradient(135deg, #f8fafc 50%, #111a27 50%); } .tp-system .side { background: linear-gradient(180deg, #14213d 50%, #070d16 50%); }
        .tp-system .bar { background: #94a3b8; } .tp-system .bar.acc { background: #2ec4c6; width: 60%; }

  @media (min-width: 861px) {
    body {
        background: #f0fafa;
    }
    .page-header {
        background: rgba(255,255,255,0.9);
        backdrop-filter: blur(8px);
        border-bottom: 1px solid #dbeeee;
        padding: 16px 24px;
    }
    .page-header .back-btn { background: transparent; color: #0d9488; }
    .page-header .back-btn:hover { background: #eafbfa; }
    .page-header h1 { color: #14213d; }
    .page-header p { color: #64748b; }
  }
</style>
<style id="rk-dark-theme">
/* Dark theme — generated by scripts/dark-theme/generate.py, do not edit by hand.
   Hand-made fixes go in resources/views/partials/dark-fixes.blade.php */
html[data-theme="dark"] body { background-image: linear-gradient(120deg, #0c1320, #112031, #1d6869, #0c1320); }
@media (min-width: 861px) {
  html[data-theme="dark"] body { background: #10161f; }
  html[data-theme="dark"] .page-header { background: rgba(23, 32, 45, 0.9); border-bottom: 1px solid #284848; }
  html[data-theme="dark"] .page-header .back-btn { color: #41eedf; }
  html[data-theme="dark"] .page-header .back-btn:hover { background: #1c3b39; }
  html[data-theme="dark"] .page-header h1 { color: #dee1e9; }
  html[data-theme="dark"] .page-header p { color: #b0b6be; }
}
</style>
</head>

<body class="min-h-screen">

@include('partials.app-nav', ['active' => 'profile'])

<div class="bg-blob b1"></div>
<div class="bg-blob b2"></div>
<div class="bg-blob b3"></div>

    <!-- Header -->
    <div class="page-header">

        <a href="{{ route('student.profile') }}" class="back-btn" aria-label="{{ __('Back') }}">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="M15 19l-7-7 7-7"/>
            </svg>
        </a>

        <div>
            <h1>{{ __('Appearance') }}</h1>
            <p>{{ __('Choose light or dark mode for RakanKampus') }}</p>
        </div>

    </div>

    <div class="max-w-md mx-auto p-5 space-y-5">

        @if(session('success'))
            <div class="rounded-xl bg-green-50 text-green-700 px-4 py-3 text-sm text-center">
                {{ session('success') }}
            </div>
        @endif

        <form method="POST" action="{{ route('student.profile.appearance.update') }}">
            @csrf
            @method('PUT')

            <div class="bg-white rounded-3xl border border-indigo-100 overflow-hidden shadow-sm">

                <div class="px-5 pt-4 pb-2">
                    <p class="text-[11px] font-bold tracking-wider uppercase text-indigo-500">{{ __('Theme') }}</p>
                </div>

                <div class="divide-y divide-indigo-50">

                    @foreach ([
                        'light' => [__('Light'), __('Bright background, best in daylight')],
                        'dark' => [__('Dark'), __('Easier on the eyes at night')],
                        'system' => [__('Use device setting'), __('Follows your phone or computer automatically')],
                    ] as $value => [$label, $hint])
                        <label class="flex items-center justify-between gap-4 px-5 py-4 cursor-pointer hover:bg-indigo-50 transition">

                            <div class="flex items-center gap-4">
                                <div class="theme-preview tp-{{ $value }}" aria-hidden="true">
                                    <div class="side"></div>
                                    <div class="main"><div class="bar acc"></div><div class="bar"></div><div class="bar" style="width:75%"></div></div>
                                </div>
                                <div>
                                    <p class="font-semibold text-indigo-900">{{ $label }}</p>
                                    <p class="text-sm text-indigo-400">{{ $hint }}</p>
                                </div>
                            </div>

                            <input type="radio" name="theme" value="{{ $value }}"
                                   class="w-5 h-5 accent-indigo-600 shrink-0"
                                   {{ $currentTheme === $value ? 'checked' : '' }}
                                   onchange="window.rkApplyTheme && window.rkApplyTheme(this.value); this.form.submit()">

                        </label>
                    @endforeach

                </div>

            </div>

        </form>

        <p class="text-xs text-indigo-300 text-center px-4">
            {{ __('Your choice is saved to your account, so it follows you to every device you sign in on.') }}
        </p>

    </div>

</body>
</html>
