<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @include('partials.pwa-head')
    <title>{{ __('Notification Settings') }}</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script>
        tailwind.config = {
            theme: {
                extend: {
                    colors: {
                        indigo: {
                            50: '#e6fbfa',
                            100: '#dbeeee',
                            200: '#b8e6e6',
                            300: '#94a3b8',
                            400: '#64748b',
                            500: '#0d9488',
                            600: '#0d9488',
                            700: '#0f766e',
                            900: '#14213d',
                        },
                    },
                },
            },
        };
    </script>
    <style>
        html, body { overflow-x: hidden; }
        body {
            background: linear-gradient(120deg, #14213d, #1b3a5c, #2ec4c6, #14213d);
    background-size: 300% 300%;
    animation: gradientShift 15s ease infinite;
        }
        .bg-blob {
            position: fixed;
            border-radius: 9999px;
            filter: blur(50px);
            opacity: 0.5;
            z-index: -1;
            pointer-events: none;
            animation: blobFloat 16s ease-in-out infinite;
        }
        .bg-blob.b1 { width: 260px; height: 260px; top: -70px; left: -80px; background: rgba(255,255,255,0.28); animation-duration: 17s; }
        .bg-blob.b2 { width: 220px; height: 220px; top: 35%; right: -90px; background: rgba(255,255,255,0.20); animation-duration: 20s; animation-delay: -4s; }
        .bg-blob.b3 { width: 200px; height: 200px; bottom: -60px; left: 15%; background: rgba(255,255,255,0.24); animation-duration: 15s; animation-delay: -8s; }
        @keyframes blobFloat {
            0%, 100% { transform: translate(0, 0) scale(1); }
            50% { transform: translate(18px, -26px) scale(1.06); }
        }
        @keyframes fadeInUp {
            from { opacity: 0; transform: translateY(14px); }
            to { opacity: 1; transform: translateY(0); }
        }
        body > div:not(.bg-blob) { animation: fadeInUp 0.45s ease both; }

        .page-header {
            display: flex;
            align-items: center;
            gap: 12px;
            padding: 20px 20px 18px;
            position: relative;
            z-index: 1;
        }
        .page-header .back-btn {
            width: 38px; height: 38px; min-width: 38px; border-radius: 50%;
            background: rgba(255,255,255,0.12);
            display: flex; align-items: center; justify-content: center;
            color: #fff; text-decoration: none; transition: background 0.15s ease;
        }
        .page-header .back-btn:hover { background: rgba(255,255,255,0.2); }
        .page-header .back-btn svg { width: 18px; height: 18px; stroke: currentColor; }
        .page-header h1 { font-size: 18px; font-weight: 800; color: #fff; margin: 0; }
        .page-header p { font-size: 12.5px; color: #bfe9ea; margin: 2px 0 0; }

  @keyframes gradientShift {
    0% { background-position: 0% 50%; }
    50% { background-position: 100% 50%; }
    100% { background-position: 0% 50%; }
  }

  @media (min-width: 861px) {
    body {
        background: #f0fafa;
    }
    .page-header {
        background: rgba(255,255,255,0.9);
        backdrop-filter: blur(8px);
        border-bottom: 1px solid #dbeeee;
        padding: 16px 24px;
    }
    .page-header .back-btn { background: transparent; color: #0d9488; }
    .page-header .back-btn:hover { background: #eafbfa; }
    .page-header h1 { color: #14213d; }
    .page-header p { color: #64748b; }
  }
</style>
<style id="rk-dark-theme">
/* Dark theme — generated by scripts/dark-theme/generate.py, do not edit by hand.
   Hand-made fixes go in resources/views/partials/dark-fixes.blade.php */
html[data-theme="dark"] body { background-image: linear-gradient(120deg, #0c1320, #112031, #1d6869, #0c1320); }
@media (min-width: 861px) {
  html[data-theme="dark"] body { background: #10161f; }
  html[data-theme="dark"] .page-header { background: rgba(23, 32, 45, 0.9); border-bottom: 1px solid #284848; }
  html[data-theme="dark"] .page-header .back-btn { color: #2feddc; }
  html[data-theme="dark"] .page-header .back-btn:hover { background: #1c3b39; }
  html[data-theme="dark"] .page-header h1 { color: #cfd4e0; }
  html[data-theme="dark"] .page-header p { color: #979faa; }
}
</style>
</head>

<body class="min-h-screen">

@include('partials.app-nav', ['active' => 'profile'])

<div class="bg-blob b1"></div>
<div class="bg-blob b2"></div>
<div class="bg-blob b3"></div>


    <!-- Header -->
    <div class="page-header">

        <a href="{{ route('student.profile') }}" class="back-btn" aria-label="{{ __('Back') }}">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="M15 19l-7-7 7-7"/>
            </svg>
        </a>

        <div>
            <h1>{{ __('Notification Settings') }}</h1>
            <p>{{ __('Manage how RakanKampus keeps you informed') }}</p>
        </div>

    </div>

    <div class="max-w-2xl mx-auto px-6 py-6 space-y-6">

        @if(session('success'))
            <div class="rounded-xl bg-green-50 text-green-700 px-4 py-3 text-sm">
                {{ session('success') }}
            </div>
        @endif

        <form id="notifForm" method="POST" action="{{ route('student.profile.notifications.update') }}" class="space-y-6">
            @csrf
            @method('PUT')

            <!-- Push notifications (read by reminders:send-due and the class "starting soon" job) -->
            <div class="bg-white rounded-3xl border border-indigo-100 overflow-hidden shadow-sm">
                <div class="px-5 pt-5 pb-3">
                    <p class="text-[11px] font-bold tracking-wider uppercase text-indigo-500">{{ __('Push notifications') }}</p>
                </div>
                <div class="divide-y divide-indigo-50">
                    <div class="flex items-center justify-between gap-4 px-5 py-4">
                        <div class="flex items-center gap-4">
                            <div class="w-11 h-11 rounded-2xl bg-indigo-50 flex items-center justify-center shrink-0">
                                <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 text-indigo-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3M12 3a9 9 0 100 18 9 9 0 000-18z"/>
                                </svg>
                            </div>
                            <div>
                                <p class="font-semibold text-indigo-900">{{ __('Reminder notifications') }}</p>
                                <p class="text-sm text-indigo-400">{{ __("Exams, assignments & quizzes before they're due") }}</p>
                            </div>
                        </div>
                        <label class="relative inline-flex items-center cursor-pointer shrink-0">
                            <input type="checkbox" name="reminder_notifications" data-notif value="1" {{ $settings['reminder_notifications'] ? 'checked' : '' }} class="sr-only peer">
                            <div class="w-11 h-6 bg-indigo-200 rounded-full peer peer-checked:bg-indigo-600 transition"></div>
                            <div class="absolute left-1 top-1 w-4 h-4 bg-white rounded-full transition peer-checked:translate-x-5"></div>
                        </label>
                    </div>
                    <div class="flex items-center justify-between gap-4 px-5 py-4">
                        <div class="flex items-center gap-4">
                            <div class="w-11 h-11 rounded-2xl bg-indigo-50 flex items-center justify-center shrink-0">
                                <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 text-indigo-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10m-11 9h12a2 2 0 002-2V7a2 2 0 00-2-2H6a2 2 0 00-2 2v11a2 2 0 002 2z"/>
                                </svg>
                            </div>
                            <div>
                                <p class="font-semibold text-indigo-900">{{ __('Class starting soon') }}</p>
                                <p class="text-sm text-indigo-400">{{ __('A heads-up before each class in your timetable') }}</p>
                            </div>
                        </div>
                        <label class="relative inline-flex items-center cursor-pointer shrink-0">
                            <input type="checkbox" name="class_notifications" data-notif value="1" {{ $settings['class_notifications'] ? 'checked' : '' }} class="sr-only peer">
                            <div class="w-11 h-6 bg-indigo-200 rounded-full peer peer-checked:bg-indigo-600 transition"></div>
                            <div class="absolute left-1 top-1 w-4 h-4 bg-white rounded-full transition peer-checked:translate-x-5"></div>
                        </label>
                    </div>
                </div>
            </div>

            <!-- Quiet time -->
            <div class="bg-white rounded-3xl border border-indigo-100 p-5 shadow-sm">
                <div class="mb-4">
                    <p class="text-[11px] font-bold tracking-wider uppercase text-indigo-500">{{ __('Quiet time') }}</p>
                </div>
                <label for="dnd_until" class="block text-sm font-semibold text-indigo-900 mb-2">{{ __('Do Not Disturb Until') }}</label>
                <input type="datetime-local" id="dnd_until" name="dnd_until" value="{{ $settings['dnd_until'] }}"
                       class="w-full rounded-2xl border border-indigo-200 bg-white px-4 py-3 text-indigo-900 focus:outline-none focus:ring-2 focus:ring-indigo-400">
                <p class="text-xs text-indigo-400 mt-2">{{ __('No notifications are sent until this time. Leave empty to turn it off.') }}</p>
            </div>

            <!-- Save -->
            <button type="submit" class="w-full rounded-2xl bg-indigo-600 py-4 text-lg font-bold text-white shadow-lg shadow-indigo-200 hover:bg-indigo-700 transition duration-200">

                {{ __('Save Notification Settings') }}

            </button>

        </form>

    </div>

<script>
// Turning a notification off asks first with a RakanKampus popup (the robot mutes a ringing bell),
// then saves straight away; a toast confirms it with UNDO. Turning one on just saves + toast.
(function () {
    const form = document.getElementById('notifForm');
    const INFO = {
        reminder_notifications: {
            prop: 'clock',
            title: @js(__('Turn off reminder notifications?')),
            message: @js(__("You won't get alerts before your exams, assignments and quizzes are due. You can turn it back on anytime.")),
            offText: @js(__('Reminder notifications off')), onText: @js(__('Reminder notifications on')),
            onSub: @js(__("We'll remind you before things are due")),
        },
        class_notifications: {
            prop: 'cal',
            title: @js(__('Turn off class alerts?')),
            message: @js(__("You won't get a heads-up before your classes start. You can turn it back on anytime.")),
            offText: @js(__('Class alerts off')), onText: @js(__('Class alerts on')),
            onSub: @js(__("We'll let you know before each class")),
        },
    };
    const T = { turnOff: @js(__('Turn off')), keepOn: @js(__('Keep on')), saved: @js(__('Saved')), oops: @js(__('Oops!')), failed: @js(__('Could not save your settings. Please try again.')) };

    async function save(cb, info) {
        try {
            const res = await fetch(form.action, { method: 'POST', body: new FormData(form), headers: { 'X-Requested-With': 'XMLHttpRequest' } });
            if (!res.ok) throw new Error(res.status);
        } catch (e) {
            cb.checked = !cb.checked;                     // put the switch back the way it was
            RKDialog.alert({ scene: 'oops', title: T.oops, message: T.failed });
            return;
        }
        const on = cb.checked;
        RKToast.show({
            text: on ? info.onText : info.offText,
            sub: on ? info.onSub : T.saved,
            undo: on ? null : () => { cb.checked = true; save(cb, info); },
        });
    }

    document.querySelectorAll('input[data-notif]').forEach(cb => cb.addEventListener('change', async () => {
        const info = INFO[cb.name];
        if (!cb.checked) {
            cb.checked = true;                            // stays on until they confirm
            const ok = await RKDialog.confirm({
                scene: 'mute', prop: info.prop, title: info.title, message: info.message,
                confirmText: T.turnOff, cancelText: T.keepOn,
            });
            if (!ok) return;
            cb.checked = false;
        }
        save(cb, info);
    }));
})();
</script>

</body>
</html>