<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @include('partials.pwa-head')
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ __('Privacy & Security') }}</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script>
        tailwind.config = {
            theme: {
                extend: {
                    colors: {
                        indigo: {
                            50: '#e6fbfa',
                            100: '#dbeeee',
                            200: '#b8e6e6',
                            300: '#94a3b8',
                            400: '#64748b',
                            500: '#0d9488',
                            600: '#0d9488',
                            700: '#0f766e',
                            900: '#14213d',
                        },
                    },
                },
            },
        };
    </script>
    <style>
        html, body { overflow-x: hidden; }
        body {
            background: linear-gradient(120deg, #14213d, #1b3a5c, #2ec4c6, #14213d);
    background-size: 300% 300%;
    animation: gradientShift 15s ease infinite;
        }
        .bg-blob {
            position: fixed;
            border-radius: 9999px;
            filter: blur(50px);
            opacity: 0.5;
            z-index: -1;
            pointer-events: none;
            animation: blobFloat 16s ease-in-out infinite;
        }
        .bg-blob.b1 { width: 260px; height: 260px; top: -70px; left: -80px; background: rgba(255,255,255,0.28); animation-duration: 17s; }
        .bg-blob.b2 { width: 220px; height: 220px; top: 35%; right: -90px; background: rgba(255,255,255,0.20); animation-duration: 20s; animation-delay: -4s; }
        .bg-blob.b3 { width: 200px; height: 200px; bottom: -60px; left: 15%; background: rgba(255,255,255,0.24); animation-duration: 15s; animation-delay: -8s; }
        @keyframes blobFloat {
            0%, 100% { transform: translate(0, 0) scale(1); }
            50% { transform: translate(18px, -26px) scale(1.06); }
        }
        @keyframes fadeInUp {
            from { opacity: 0; transform: translateY(14px); }
            to { opacity: 1; transform: translateY(0); }
        }
        body > div:not(.bg-blob) { animation: fadeInUp 0.45s ease both; }

        .page-header {
            display: flex;
            align-items: center;
            gap: 12px;
            padding: 20px 20px 18px;
            position: relative;
            z-index: 1;
        }
        .page-header .back-btn {
            width: 38px; height: 38px; min-width: 38px; border-radius: 50%;
            background: rgba(255,255,255,0.12);
            display: flex; align-items: center; justify-content: center;
            color: #fff; text-decoration: none; transition: background 0.15s ease;
        }
        .page-header .back-btn:hover { background: rgba(255,255,255,0.2); }
        .page-header .back-btn svg { width: 18px; height: 18px; stroke: currentColor; }
        .page-header h1 { font-size: 18px; font-weight: 800; color: #fff; margin: 0; }
        .page-header p { font-size: 12.5px; color: #bfe9ea; margin: 2px 0 0; }

  @keyframes gradientShift {
    0% { background-position: 0% 50%; }
    50% { background-position: 100% 50%; }
    100% { background-position: 0% 50%; }
  }

  @media (min-width: 861px) {
    body {
        background: #f0fafa;
    }
    .page-header {
        background: rgba(255,255,255,0.9);
        backdrop-filter: blur(8px);
        border-bottom: 1px solid #dbeeee;
        padding: 16px 24px;
    }
    .page-header .back-btn { background: transparent; color: #0d9488; }
    .page-header .back-btn:hover { background: #eafbfa; }
    .page-header h1 { color: #14213d; }
    .page-header p { color: #64748b; }
  }
</style>
<style id="rk-dark-theme">
/* Dark theme — generated by scripts/dark-theme/generate.py, do not edit by hand.
   Hand-made fixes go in resources/views/partials/dark-fixes.blade.php */
html[data-theme="dark"] body { background-image: linear-gradient(120deg, #0c1320, #112031, #1d6869, #0c1320); }
@media (min-width: 861px) {
  html[data-theme="dark"] body { background: #10161f; }
  html[data-theme="dark"] .page-header { background: rgba(23, 32, 45, 0.9); border-bottom: 1px solid #284848; }
  html[data-theme="dark"] .page-header .back-btn { color: #41eedf; }
  html[data-theme="dark"] .page-header .back-btn:hover { background: #1c3b39; }
  html[data-theme="dark"] .page-header h1 { color: #dee1e9; }
  html[data-theme="dark"] .page-header p { color: #b0b6be; }
}
</style>
</head>

<body class="min-h-screen">

@include('partials.app-nav', ['active' => 'profile'])

<div class="bg-blob b1"></div>
<div class="bg-blob b2"></div>
<div class="bg-blob b3"></div>

    <!-- Header -->
    <div class="page-header">

        <a href="{{ route('student.profile') }}" class="back-btn" aria-label="{{ __('Back') }}">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="M15 19l-7-7 7-7"/>
            </svg>
        </a>

        <div>
            <h1>{{ __('Privacy & Security') }}</h1>
            <p>{{ __('Devices, sign-in history and your data') }}</p>
        </div>

    </div>

    <div class="max-w-md mx-auto p-5 space-y-5">

        @if(session('success'))
            <div class="rounded-xl bg-green-50 text-green-700 px-4 py-3 text-sm text-center">
                {{ session('success') }}
            </div>
        @endif

        <!-- Signed-in devices -->
        <div class="bg-white rounded-3xl border border-indigo-100 overflow-hidden shadow-sm">
            <div class="px-5 pt-4 pb-2">
                <p class="text-[11px] font-bold tracking-wider uppercase text-indigo-500">{{ __('Signed-in devices') }}</p>
            </div>

            <div class="divide-y divide-indigo-50">
                @foreach($devices as $d)
                    <div class="flex items-center gap-4 px-5 py-4">
                        <div class="w-11 h-11 rounded-2xl bg-indigo-50 flex items-center justify-center shrink-0">
                            <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 text-indigo-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                @if($d->mobile)<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 2h8a2 2 0 012 2v16a2 2 0 01-2 2H8a2 2 0 01-2-2V4a2 2 0 012-2zM11 18h2"/>@else<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 5h16v11H4zM2 19h20"/>@endif
                            </svg>
                        </div>
                        <div class="flex-1 min-w-0">
                            <p class="font-semibold text-indigo-900 truncate">{{ $d->name }}</p>
                            <p class="text-sm text-indigo-400">
                                @if($d->current)
                                    <span class="text-green-600 font-medium">● {{ __('This device') }}</span>
                                @else
                                    {{ __('Active :time', ['time' => $d->last_active->diffForHumans()]) }}
                                @endif
                                @if($d->ip) · {{ $d->ip }} @endif
                            </p>
                        </div>
                        @unless($d->current)
                            <form method="POST" action="{{ route('student.profile.devices.logout', $d->id) }}"
                                  onsubmit="return RKDialog.confirmForm(event, { scene: 'signout', title: @js(__('Sign out this device?')), message: @js(__('It will need to log in again to use RakanKampus.')), list: [{ label: @js($d->name) }], confirmText: @js(__('Sign out')) })">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="text-sm font-semibold text-red-600 hover:bg-red-50 rounded-xl px-3 py-2">{{ __('Sign out') }}</button>
                            </form>
                        @endunless
                    </div>
                @endforeach
            </div>

            @if($devices->where('current', false)->isNotEmpty())
                <form method="POST" action="{{ route('student.profile.devices.logout-others') }}" class="px-5 pb-5 pt-1"
                      onsubmit="return RKDialog.confirmForm(event, { scene: 'signout', title: @js(__('Sign out all other devices?')), message: @js(__('You will stay signed in here.')), pill: @js(trans_choice(':count device|:count devices', $devices->where('current', false)->count())), confirmText: @js(__('Sign out all')) })">
                    @csrf
                    <button type="submit" class="w-full rounded-2xl border border-red-200 py-3 font-semibold text-red-600 hover:bg-red-50 transition">
                        {{ __('Sign out all other devices') }}
                    </button>
                </form>
            @endif
        </div>

        <!-- Recent sign-ins -->
        <div class="bg-white rounded-3xl border border-indigo-100 overflow-hidden shadow-sm">
            <div class="px-5 pt-4 pb-2">
                <p class="text-[11px] font-bold tracking-wider uppercase text-indigo-500">{{ __('Recent sign-ins') }}</p>
            </div>
            @if($logins->isEmpty())
                <p class="px-5 pb-5 text-sm text-indigo-400">{{ __('Your sign-ins will appear here from your next login.') }}</p>
            @else
                <div class="divide-y divide-indigo-50">
                    @foreach($logins as $l)
                        <div class="flex items-center justify-between gap-4 px-5 py-3">
                            <div class="min-w-0">
                                <p class="font-medium text-indigo-900 truncate">{{ $l->name }}</p>
                                <p class="text-sm text-indigo-400">{{ $l->at->format('d M Y, g:i A') }}@if($l->ip) · {{ $l->ip }}@endif</p>
                            </div>
                            <span class="text-xs text-indigo-400 shrink-0">{{ $l->at->diffForHumans() }}</span>
                        </div>
                    @endforeach
                </div>
            @endif
        </div>

        <!-- Password + data -->
        <div class="bg-white rounded-3xl border border-indigo-100 overflow-hidden shadow-sm">
            <div class="px-5 pt-4 pb-2">
                <p class="text-[11px] font-bold tracking-wider uppercase text-indigo-500">{{ __('Account & data') }}</p>
            </div>

            <div class="divide-y divide-indigo-50">
                <a href="{{ route('student.profile.password') }}" class="flex items-center justify-between px-5 py-4 hover:bg-indigo-50 transition">
                    <div class="flex items-center gap-4">
                        <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 text-indigo-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 11h12v9H6zM8 11V8a4 4 0 118 0v3"/>
                        </svg>
                        <div>
                            <p class="font-semibold text-indigo-900">{{ __('Change Password') }}</p>
                            <p class="text-sm text-indigo-400">{{ __('Use a strong password you do not use elsewhere') }}</p>
                        </div>
                    </div>
                    <span class="text-indigo-300 text-lg">›</span>
                </a>

                <a href="{{ route('student.profile.data.download') }}" class="flex items-center justify-between px-5 py-4 hover:bg-indigo-50 transition">
                    <div class="flex items-center gap-4">
                        <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 text-indigo-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v11m0 0l-4-4m4 4l4-4M5 20h14"/>
                        </svg>
                        <div>
                            <p class="font-semibold text-indigo-900">{{ __('Download my data') }}</p>
                            <p class="text-sm text-indigo-400">{{ __('Profile, chats, reminders and timetable as a file') }}</p>
                        </div>
                    </div>
                    <span class="text-indigo-300 text-lg">›</span>
                </a>

                <form method="POST" action="{{ route('student.profile.chats.clear') }}"
                      onsubmit="return RKDialog.confirmForm(event, { scene: 'chat', title: @js(__('Delete all conversations?')), message: @js(__('Every chat with RakanKampus will be removed.')), pill: @js(trans_choice(':count conversation|:count conversations', $chatCount)), warn: @js(__('This cannot be undone.')), confirmText: @js(__('Delete all')) })">
                    @csrf
                    @method('DELETE')
                    <button type="submit" @disabled($chatCount === 0)
                            class="w-full flex items-center justify-between px-5 py-4 hover:bg-red-50 transition text-left disabled:opacity-50 disabled:cursor-default disabled:hover:bg-transparent">
                        <div class="flex items-center gap-4">
                            <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 text-red-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 7h16M10 11v6m4-6v6M6 7l1 13h10l1-13M9 7V4h6v3"/>
                            </svg>
                            <div>
                                <p class="font-semibold text-red-600">{{ __('Clear chat history') }}</p>
                                <p class="text-sm text-indigo-400">{{ trans_choice('{0} No saved conversations|{1} 1 saved conversation|[2,*] :count saved conversations', $chatCount, ['count' => $chatCount]) }}</p>
                            </div>
                        </div>
                    </button>
                </form>
            </div>
        </div>

    </div>

</body>
</html>
